// @ts-check
// The wiki sidebar is generated automatically from the docs/ folder structure.
// Ordering comes from `sidebar_position` in each doc's frontmatter and from the
// `position`/`label` fields in each folder's _category_.json.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
